name: Gun
main: gun\Main
version: "α7.0"
api: [1.12.0,2.0.0,3.0.0]
load: POSTWORLD
permissions:
 battlefront:
  default: op
  description: このプラグインの全機能を使用することを許可します
  children:
   battlefront.command:
    default: op
    description: このプラグインによって追加されるコマンドのすべてを使用することを許可します
    children:
     battlefront.command.npc:
      default: op
      description: NPC管理用コマンドを使用することを許可します
     battlefront.command.weapon:
      default: op
      description: 武器管理用コマンドを使用することを許可します
     battlefront.command.weaponshop:
      default: true
      description: 武器ショップコマンドを使用することを許可します
     battlefront.command.guidebook:
      default: op
      description: ガイドブック管理用コマンドを使用することを許可します
     battlefront.command.game:
      default: op
      description: ゲーム用コマンドを使用することを許可します
     battlefront.command.discord:
      default: op
      description: Discord連携管理用コマンドを使用することを許可します
     battlefront.command.ranking:
      default: op
      description: ランキング関連コマンドを使用することを許可します
     battlefront.command.summon:
      default: op
      description: Entity召喚関連コマンドを使用することを許可します
     battlefront.command.testfire:
      default: true
      description: 試し打ち関連コマンドを使用することを許可します
     battlefront.command.mystatus:
      default: true
      description: ステータスを確認することを許可します
     battlefront.command.jobshop:
      default: true
      description: ジョブショップコマンドを使用することを許可します
